dist: trusty
language: c++

os:
  - linux

notifications:
  email:
    recipients:
      - asg@airmail.cc
    on_success: never
    on_failure: never

addons:
  apt:
    packages:
    - g++

script:
  - g++ steg.cpp